"""add_product_mockup_design_fields

Revision ID: 2b256250b7cd
Revises: c8b7eb179953
Create Date: 2026-04-06 21:38:21.370563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b256250b7cd'
down_revision: Union[str, Sequence[str], None] = 'c8b7eb179953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printful_catalog_product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('design_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mockup_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('placement_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('placement_json')
        batch_op.drop_column('mockup_url')
        batch_op.drop_column('design_url')
        batch_op.drop_column('printful_catalog_product_id')

    # ### end Alembic commands ###
