"""add_product_types_table_and_catalogue_fk

Revision ID: 8a2aba93c388
Revises: 29ca7923bed1
Create Date: 2026-04-08 11:23:01.936155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2aba93c388'
down_revision: Union[str, Sequence[str], None] = '29ca7923bed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('product_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_types_slug'), ['slug'], unique=True)

    with op.batch_alter_table('catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_catalogue_product_type_id', 'product_types', ['product_type_id'], ['id'], ondelete='SET NULL')

    # ── Seed des 4 types de produits par défaut ─────────────────────────────
    product_types_table = sa.table(
        'product_types',
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('description', sa.Text),
    )
    op.bulk_insert(product_types_table, [
        {
            "name": "T-SHIRTS PREMIUM",
            "slug": "t-shirts-premium",
            "description": "T-shirts Premium DTG impression directe sur tissu. 100% coton bio. Coupe unisexe oversize. Lavage à 30°C. Résiste aux regards médiocres.",
        },
        {
            "name": "HOODIES OVERSIZE",
            "slug": "hoodies-oversize",
            "description": "Hoodies Heavy Cotton 400g/m², taille oversize. Pour les longues sessions de compilation et les crises existentielles. Capuche double épaisseur.",
        },
        {
            "name": "XXXL PAD",
            "slug": "xxxl-pad",
            "description": "Tapis de bureau XXXL 90×45cm. Surface microfibre anti-glitch. Base antidérapante. Pattern généré par data stream en temps réel. Pour dominer le chaos.",
        },
        {
            "name": "STICKERS",
            "slug": "stickers",
            "description": "Stickers die-cut vinyle waterproof. Découpe à la forme, impression haute saturation. Résiste à l'eau, au soleil et aux opinions non sollicitées.",
        },
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogue', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catalogue_product_type_id', type_='foreignkey')
        batch_op.drop_column('product_type_id')

    with op.batch_alter_table('product_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_types_slug'))
        batch_op.drop_index(batch_op.f('ix_product_types_id'))

    op.drop_table('product_types')
    # ### end Alembic commands ###
