"""add ProductVariant ShopDesign catalogue fields

Revision ID: bea371a5449f
Revises: 069b94c7359f
Create Date: 2026-04-07 22:56:35.280487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea371a5449f'
down_revision: Union[str, Sequence[str], None] = '069b94c7359f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('dpi', sa.Float(), nullable=True),
    sa.Column('print_ready', sa.Integer(), nullable=False),
    sa.Column('bg_removed', sa.Integer(), nullable=False),
    sa.Column('upscaled', sa.Integer(), nullable=False),
    sa.Column('vectorized', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_designs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_designs_id'), ['id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('printful_variant_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('printful_cost_ht', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printful_variant_id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variants_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('design_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('placement_json', sa.Text(), nullable=True))

    # ── Migration de données : chaque Product existant → 1 ProductVariant ──
    conn = op.get_bind()
    products = conn.execute(
        sa.text("SELECT id, printful_variant_id, printful_cost_ht, price, name FROM products")
    ).fetchall()
    for prod in products:
        variant_name = str(prod[4] or "")
        # Tenter de parser couleur/taille depuis le suffixe " — Color / Size"
        color, size = None, None
        if " — " in variant_name:
            suffix = variant_name.split(" — ", 1)[1]
            parts = [p.strip() for p in suffix.split("/")]
            if len(parts) >= 2:
                color = parts[0]
                size = parts[1]
            elif len(parts) == 1:
                size = parts[0]
        conn.execute(
            sa.text(
                "INSERT INTO product_variants "
                "(product_id, printful_variant_id, color, size, printful_cost_ht, price) "
                "VALUES (:pid, :vid, :color, :size, :cost, :price)"
            ),
            {"pid": prod[0], "vid": prod[1], "color": color, "size": size,
             "cost": prod[2], "price": prod[3]},
        )
    # ────────────────────────────────────────────────────────────────────────

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('printful_variant_id')
        batch_op.drop_column('printful_cost_ht')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printful_cost_ht', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('printful_variant_id', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('catalogue', schema=None) as batch_op:
        batch_op.drop_column('placement_json')
        batch_op.drop_column('design_url')
        batch_op.drop_column('variants_json')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_variants_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('shop_designs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_designs_id'))

    op.drop_table('shop_designs')
    # ### end Alembic commands ###
