"""alter_promo_code_discount_type

Revision ID: c30dda6e27fd
Revises: dfbb039216c1
Create Date: 2026-04-06 14:44:42.544297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30dda6e27fd'
down_revision: Union[str, Sequence[str], None] = 'dfbb039216c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_type', sa.String(), nullable=False, server_default='percent'))
        batch_op.add_column(sa.Column('discount_value', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.alter_column('max_uses',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
        batch_op.drop_column('discount_percent')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.INTEGER(), nullable=False))
        batch_op.alter_column('max_uses',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_type')

    # ### end Alembic commands ###
