"""product_pricing_breakdown

Revision ID: c8b7eb179953
Revises: 09c5399d757d
Create Date: 2026-04-06 16:34:39.968603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b7eb179953'
down_revision: Union[str, Sequence[str], None] = '09c5399d757d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_price_ht', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('printful_cost_ht', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('shop_margin_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('tva_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tva_rate')
        batch_op.drop_column('shop_margin_rate')
        batch_op.drop_column('printful_cost_ht')
        batch_op.drop_column('design_price_ht')

    # ### end Alembic commands ###
