"""add_invoice_addresses

Revision ID: f7e726b74290
Revises: bfd9cb65fa68
Create Date: 2026-04-06 11:47:27.808833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e726b74290'
down_revision: Union[str, Sequence[str], None] = 'bfd9cb65fa68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('billing_address', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('shipping_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'shipping_address')
    op.drop_column('invoices', 'billing_address')
    # ### end Alembic commands ###
